CREATE TABLE "duplicates" (
    "CTX_merchantId"    TEXT,
    "CTX_name"    TEXT,
    "CTX_address1"    TEXT,
    "CTX_address2"    TEXT,
    "CTX_address3"    TEXT,
    "CTX_address4"    TEXT,
    "CTX_latitude"    REAL,
    "CTX_longitude"    REAL,
    "CTX_website"    TEXT,
    "CTX_phone"    TEXT,
    "CTX_territory"    TEXT,
    "CTX_city"    TEXT,
    "CTX_source"    TEXT,
    "CTX_sourceId"    TEXT,
    "PiggyCards_merchantId"    TEXT,
    "PiggyCards_name"    TEXT,
    "PiggyCards_address1"    TEXT,
    "PiggyCards_address2"    TEXT,
    "PiggyCards_address3"    TEXT,
    "PiggyCards_address4"    TEXT,
    "PiggyCards_latitude"    REAL,
    "PiggyCards_longitude"    REAL,
    "PiggyCards_territory"    TEXT,
    "PiggyCards_city"    TEXT,
    "PiggyCards_source"    TEXT,
    "PiggyCards_sourceId"    TEXT
);